# Pandasda sık kullanılan fonksiyon ve metodlar

# Bu kısımda bulunan bazı built-in functionları ve metodlar olucak.
- apply() method
- apply() with a function
- apply() with a lambda expression
- apply() on multipile columns
- describe()
- sort_values()
- corr()
- idxmın and idxmax()
- value counts()
- replace()
- unique and runique()
- map()
- duplicate and drop duplicate()
- between()
- sample ()
- nlargest()

In [1]:
import numpy as np
import pandas as pd

In [36]:
df = pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# .apply() Methodu

In [8]:
# .apply() methodu bir series ya da dataframe'in stğnlarındaki değerlerın hepsini bir anda bir fonksiyon uygulamaya yarar.
# arka planında for döngüsü çalışır dolayısıyla çok hızlı değildir performans açısından vetkörize işlemleri uygulamak daha faydalıdır.
# özellikle vektörize edilmiş işlemler hızlı çalışır ve for döngüsü kullanımını minimize eder.
# ancak .apply() methodunu kulanmak oldukça okunaklı ve başlangıçta kolaydır.

In [9]:
# amaç cc number sutünunun son 4 rakamını almak ve bu şekilde güncellemek.

## 1. yol

In [14]:
# def son4(x):
#  return str(x)[-4:]

In [15]:
# df['CC Number']= df['CC Number'].apply(son4)

In [13]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,9230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,1322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,5994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,7221,Sun2251

## 2.yol

In [21]:
# df['CC Number'] = df['CC Number'].apply(lambda x: str(x)[-4:])

In [22]:
# df.head()

## 3.yol (vektöriezd)(en hızlısı)

In [27]:
df['CC Number'].astype(str).str[-4:]
# daha hızlı işlem

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [30]:
# amaç: 10 dolardan az ödediyse ($) 10 ile 30 arası
# ($$) 30 dan fazla ödediyse ($$$) işareti bulunan
# fiyat kategorisi adında bir sütun oluştur

### 1. yol

In [37]:
# def fiyat_kategorisi(x):
#  if x < 10 :
#    return '$'
#  elif 10 <= x < 30 :
#    return '$$'
#  else :
#    return '$$$'

In [38]:
# df['fiyat kategorisi']= df['total_bill'].apply(fiyat_kategorisi)

In [39]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

### 2. yol

In [45]:
df['fiyat_kategorisi'] = df['total_bill'].apply(lambda x : '$' if x < 10 else '$$' if 10<= x <30 else '$$$' )

In [46]:
df.sample(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,fiyat_kategorisi
174,16.82,4.00,Male,Yes,Sun,Dinner,2,8.41,Brian Miles,3586342145399277,Sun7621,$$
34,17.78,3.27,Male,No,Sat,Dinner,2,8.89,Jacob Castillo,3551492000704805,Sat8124,$$

### 3. yol (en hızlısı)

In [47]:
df.drop('fiyat_kategorisi', axis = 1 , inplace = True)

In [54]:
def fiyat_kategorisi_vectorized(bill):
  categories = np.full_like(bill, '$', dtype = 'U3')

  categories[(bill > 10) & (bill < 30)] = '$$'

  categories[(bill >= 30 )] = '$$$'

  return categories

In [56]:
df['fiyat_kategorisi'] = fiyat_kategorisi_vectorized(df['total_bill'].values)

In [57]:
df.sample(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,fiyat_kategorisi
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274,$$$
61,13.81,2.00,Male,Yes,Sat,Dinner,2,6.90,Ryan Hernandez,4766834726806,Sat3030,$$
119,24.08,2.92,Female,No,Thur,Lunch,4,6.02,Melanie Jordan,676212062720,Thur8063,$$

In [89]:
df = df.drop('sex', axis=1)
display(df.head())

KeyError: "['sex'] not found in axis"

### .apply() metodu birden fazla sütuna aynı anda uygulanabilir

### 1. yol

In [58]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,fiyat_kategorisi
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,$$

In [59]:
def kareal(x):
  return x**2

In [61]:
df[['total_bill' , 'tip']].apply(kareal)

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

### 2. yol

In [62]:
df[['total_bill','tip']].apply(lambda x: x**2)

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

### 3. yol vektörize

In [63]:
np.square(df['total_bill'])

0      288.6601
1      106.9156
2      441.4201
3      560.7424
4      604.6681
         ...
239    842.7409
240    738.7524
241    513.9289
242    317.5524
243    352.6884
Name: total_bill, Length: 244, dtype: float64

In [65]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [67]:
df.sort_values('total_bill') #asc = true olduğu için küçüktn büyüğe sıraladı

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,fiyat_kategorisi
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,$
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,$
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,$
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,30432617123103,Sun9209,$
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,4823139288341889,Thur6321,$
...,...,...,...,...,...,...,...,...,...,...,...,...
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,$$$

In [86]:
# df.sort_values('total_bill',ascending = False)

In [85]:
# df.reset_index(inplace = True , drop = True) #sort ile sıralanan değerlerinin index değerlerini yeniden resetler

In [74]:
df.sample(3)

,level_0,index,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,fiyat_kategorisi
168,168,168,10.59,1.61,Female,Yes,Sat,Dinner,2,5.30,Sara Jimenez,502053147208,Sat9795,$$
110,110,110,14.00,3.00,Male,No,Sat,Dinner,2,7.00,James Sanchez,345243048851323,Sat6801,$$
64,64,64,17.59,2.64,Male,No,Sat,Dinner,3,5.86,Michael Johnson,2222114458088108,Sat1667,$$

In [84]:
# df.sort_values(['total_bill','tip'])

In [83]:
# df['price_per_person'].max()

In [82]:
# df['price_per_person'].argmax() #direk indexini getirir

In [93]:
import numpy as np

df_numeric = df.select_dtypes(include=[np.number])

# Drop 'level_0' and 'index' columns if they exist
if 'level_0' in df_numeric.columns:
    df_numeric = df_numeric.drop(columns=['level_0'])
if 'index' in df_numeric.columns:
    df_numeric = df_numeric.drop(columns=['index'])

df_numeric.corr()

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [94]:
# df.corr() makine öğrenmesi modelleri kurarken büyük öneme sahip
# numeric colmnlar arasındaki doğrusal ilişkiyi gösteriyor

In [98]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [99]:
df.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [100]:
df.day.unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [102]:
df.day.nunique() #unique değerlerin sayısı

4

In [103]:
# amaç: sex columndaki male olanları m female olanları f haline getirmek

In [109]:
df['smoker'].replace('Yes', 'y' , inplace = True )
df['smoker'].replace('No', 'N' )

/tmp/ipykernel_3438/2263876477.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['smoker'].replace('Yes', 'y' , inplace = True )

0      N
1      N
2      N
3      N
4      N
      ..
239    N
240    y
241    y
242    N
243    N
Name: smoker, Length: 244, dtype: object

In [112]:
# df['smoker'].map({'Yes':'y','No':'n'})

In [113]:
# .done