In [1]:
import numpy as np
import pandas as pd

# Missing Values (eksik veriler)

In [3]:
# Makine öğrenmesi algoritmalarının pek çoğu missing valueslarla çalışmaz bu yüzden bunlarla biz ilgilenmeliyiz
# eksik veri anlamına gelir ve değeri bilinmeyen verileri ifade eder.
# farklı formatlarda olabilir.

In [5]:
np.nan # en sık karşılaşılan eksik veri.

nan

In [7]:
pd.NA

In [9]:
np.nan == np.nan
# değerini bilmediğimiz iki veriyi bu şekilde sorgulayamayız.

False

In [10]:
df = pd.read_csv('movie_scores.csv')

In [11]:
df.sample(2)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0

In [12]:
df.isna()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [13]:
df.isna().sum()

first_name          1
last_name           1
age                 1
sex                 1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [14]:
# amaç: pre movie score sütunu nan olmayan satırları getirmek.

In [15]:
df[df['pre_movie_score'].notna()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [16]:
# amaç post movie score nan olan satırları getirmek

In [17]:
df[df['post_movie_score'].isna()]

  first_name last_name   age  sex  pre_movie_score  post_movie_score
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN

In [18]:
# pre movie score nan olan age sütunu nan olmayanları getirmek.

In [19]:
df[(df['pre_movie_score'].isna()) & (df['age'].notna())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

# Missing valuelarla yapılabilecek 3 şey vardır.

In [20]:
# 1- Dokunmadan bırakabiliriz.
# 2- Drop edebiliriz.(satır veya sütun bazlı)
# 3- Mantıklı bir şekilde doldurabiliriz.

In [21]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [24]:
# 1. yol: yapılacak hiçbir şey yok.

In [25]:
# 2. yol:

In [26]:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [28]:
df.dropna(how = 'all')
#hepsi nan olanları düşürür.

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [29]:
df.dropna(thresh = 1)
# bir tane bile nan olamyan veri varsa o satırı tut.

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [30]:
# 3. yol: Fill the data (datayı dolurmak)

In [31]:
df.head()

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [32]:
df.dropna(how = 'all',inplace=True)

In [34]:
df['pre_movie_score'].fillna(9.6)
# manuel doldurma

0    8.0
2    9.6
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [36]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())
#sütunda bulunan değerlerin ortalaması ile doldurma.

0    8.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [37]:
#.done