# Pandas Nedir ?

In [1]:
# Pandas açık kaynaklı ve ücretsiz veri işleme , manipüle etme vb. işlemlerin yapılabilineceği oldukça efektif bir kütüphanedir.
# Pandas kütüphanesi Numpy kütüphanesi üzerine kurulmuş bir kütüphanedir.
# Pandas elimizdeki veriyi şekillendirip işlememize ve veriden anlamlı sonuçlar çıkarmamıza olanak sağlar.
# Pandas kütüphanesinin temel elemanarı series ve dataframe'dir
# Series ve dataframe nesnelerini excel tabloları gibi düşünebiliriz.

# Pandas import etme

In [4]:
# !pip install Pandas
import pandas as pd

# Series oluşturma

In [6]:
my_data = ['Ali','Alper','Burak','Ahmet','Anıl']
my_data

['Ali', 'Alper', 'Burak', 'Ahmet', 'Anıl']

In [7]:
# pd.series fonksiyonu ile elimizdeki verileri seri haline getirebiliriz.

In [8]:
pd.Series(my_data)

0      Ali
1    Alper
2    Burak
3    Ahmet
4     Anıl
dtype: object

In [9]:
my_data = [1923,1776,1876]
my_idx = ['Türkiye','USA','Canada']

In [10]:
pd.Series(my_data,my_idx)

Türkiye    1923
USA        1776
Canada     1876
dtype: int64

In [11]:
pd.Series(data=my_data,index=my_idx)

Türkiye    1923
USA        1776
Canada     1876
dtype: int64

In [12]:
#pd.series fonksiyonu içerisine dictionary de alabilir.
#Dictionary'nin keyleri index value'ları değer olur.

In [13]:
my_dict = {
    'Ali': 25,
    'Kaan': 24,
    'Deniz': 29,
}

In [14]:
my_dict

{'Ali': 25, 'Kaan': 24, 'Deniz': 29}

In [15]:
pd.Series(data=my_dict)

Ali      25
Kaan     24
Deniz    29
dtype: int64

In [18]:
sorud = {
    'İstanbul': 15.4,
    'Ankara': 5.6,
    'İzmir': 4.3,
    'Bursa': 3,
}

In [19]:
sorul1 = ['İstanbul','Ankara','İzmir','Bursa']
sorul2 = [15.4 ,5.6 ,4.3 ,3]

In [20]:
pd.Series(sorud)

İstanbul    15.4
Ankara       5.6
İzmir        4.3
Bursa        3.0
dtype: float64

In [22]:
pd.Series(sorul2,sorul1)

İstanbul    15.4
Ankara       5.6
İzmir        4.3
Bursa        3.0
dtype: float64

# Serilerde İşlemler

In [24]:
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Japan': 100,'China': 500, 'India': 210,'USA': 260}

In [26]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [28]:
sales_total = sales_q1 + sales_q2

In [29]:
sales_total

Japan    180
China    950
India    410
USA      510
dtype: int64

In [31]:
sales_total.index #index attribute'ı ile bakabiliriz.

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [34]:
sales_total.keys() #keys() metoduyla da indexlerine bakabiliriz.

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [35]:
sales_total.values #.values attribute'ı ile de değerlerine bakabiliriz.

array([180, 950, 410, 510])

In [36]:
sales_total

Japan    180
China    950
India    410
USA      510
dtype: int64

In [37]:
sales_total * 2

Japan     360
China    1900
India     820
USA      1020
dtype: int64

In [38]:
sales_total / 10

Japan    18.0
China    95.0
India    41.0
USA      51.0
dtype: float64

In [40]:
sales_q2 - sales_q1

Japan    20
China    50
India    10
USA      10
dtype: int64

In [41]:
q1 = {'Japan': 80, 'China': 450, 'Turkey': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [42]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [43]:
sales_q1,

(Japan      80
 China     450
 Turkey    200
 USA       250
 dtype: int64,)

In [44]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [46]:
sales_q1 + sales_q2

Brazil      NaN
China     950.0
India       NaN
Japan       NaN
Turkey      NaN
USA       510.0
dtype: float64

In [47]:
sales_q1.add(sales_q2,fill_value=0)
#add metoduyla boşlukları nan'ları 0 ile doldurabiliyoruz.

Brazil    100.0
China     950.0
India     210.0
Japan      80.0
Turkey    200.0
USA       510.0
dtype: float64

In [49]:
sales_q1.dtype #.dtype attribute ile serinin türünü çekebiliriz.

dtype('int64')

In [50]:
league_2022 = {
    'Fenerbahce': 51,
    'Galatasaray': 60,
    'Beşiktaş': 50,
    'Trabzonspor': 48
}
league_2021 = {
    'Fenerbahce': 73,
    'Galatasaray': 68,
    'Beşiktaş': 59,
    'Trabzonspor': 81
}
league_2020 = {
    'Fenerbahce': 82,
    'Galatasaray': 84,
    'Beşiktaş': 84,
    'Trabzonspor': 71
}

In [57]:
lg_1 = pd.Series(league_2022)
lg_2 = pd.Series(league_2021)
lg_3 = pd.Series(league_2020)

In [58]:
lg_1 + lg_2 + lg_3

Fenerbahce     206
Galatasaray    212
Beşiktaş       193
Trabzonspor    200
dtype: int64

In [59]:
league_2022 = pd.Series(data= {'Fenerbahçe':51,'Galatasaray':60,'Beşiktaş':50,'Trabzonspor':48})
league_2021 = pd.Series(data= {'Fenerbahçe':73,'Galatasaray':68,'Beşiktaş':59,'Trabzonspor':81})
league_2020 = pd.Series(data= {'Fenerbahçe':82,'Galatasaray':84,'Beşiktaş':84,'Trabzonspor':71})

In [60]:
league_2020 + league_2021 + league_2022

Fenerbahçe     206
Galatasaray    212
Beşiktaş       193
Trabzonspor    200
dtype: int64

In [61]:
#done.