# Dataframe Basics

In [ ]:
# df oluşturma
# df'in içersinde bir ya da birden fazla column'u(stünunu) seçmek.
# df'in içersinde bir ya da birden fazla row'u(satırı) seçmek.
# df'in içersine bir column ya da row ekleme.

In [2]:
import numpy as np
import pandas as pd

In [ ]:
#pd.DataFrame() fonksiyonuyla basitçe df oluşturabiliriz.

In [3]:
my_data = np.random.randint(0,101,size = (5,4))
my_data

array([[40, 39, 20, 80],
       [92,  3, 79, 77],
       [79, 11, 75, 56],
       [61, 92,  5, 39],
       [94, 69, 75, 13]])

In [4]:
pd.DataFrame(my_data)

    0   1   2   3
0  40  39  20  80
1  92   3  79  77
2  79  11  75  56
3  61  92   5  39
4  94  69  75  13

In [5]:
my_idx = ['TR','BR','USA','RU']
my_cols = ['Jan','Feb','Mar']
my_data = np.random.randint(0,101,size = (4,3))

In [6]:
df = pd.DataFrame(data = my_data,index = my_idx,columns = my_cols)

In [7]:
df

     Jan  Feb  Mar
TR    25   85   13
BR    66    6   48
USA   14   19   51
RU    46   60    8

In [8]:
df.info() #.info metoduyla içindeki bütün columnların temel bilgilerini görebiliriz.

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, TR to RU
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int64
 1   Feb     4 non-null      int64
 2   Mar     4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

# Hazır bir data çağırmak

In [9]:
!pwd

/content

In [ ]:
# .csv ya da .xlsx vb dosya formatlarını df olarak okuyabiliriz.
#  .csv dosyasını okumak için pd.road_csv() fonksiyonunu kullanırız.

In [10]:
df = pd.read_csv('tips.csv')

In [11]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [12]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [13]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

In [14]:
df.tail(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [16]:
df.sample(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003
68,20.23,2.01,Male,No,Sat,Dinner,2,10.12,Mr. Travis Bailey Jr.,60406789937,Sat561

In [18]:
df.shape #244 satır , 11 sutün

(244, 11)

In [22]:
df.columns #columnların isimlerini görebiliyoruz

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [21]:
df.info() #columnların infosuna bakabiliyoruz.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [23]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [25]:
df.describe().T #numeric columnların istatistiksel tanımını , özetini verir

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

# Column İşlemleri

In [26]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [29]:
df['price_per_person']

0       8.49
1       3.45
2       7.00
3      11.84
4       6.15
       ...
239     9.68
240    13.59
241    11.34
242     8.91
243     9.39
Name: price_per_person, Length: 244, dtype: float64

In [30]:
df[['price_per_person']]

     price_per_person
0                8.49
1                3.45
2                7.00
3               11.84
4                6.15
..                ...
239              9.68
240             13.59
241             11.34
242              8.91
243              9.39

[244 rows x 1 columns]

In [31]:
df[['tip','sex']]

      tip     sex
0    1.01  Female
1    1.66    Male
2    3.50    Male
3    3.31    Male
4    3.61  Female
..    ...     ...
239  5.92    Male
240  2.00  Female
241  2.00    Male
242  1.75    Male
243  3.00  Female

[244 rows x 2 columns]

In [32]:
# amaç: İnsanların bonkörlük düzeylerini hesaplayın.
# ödediği paraya oranla ne kadar bahşiş bıraktığı
# Bonkörlük düzeyi = verilen bahşiş / ödenen toplam ücret * 100 şeklinde hesaplanır.

In [33]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [34]:
df['tip'] / df['total_bill'] * 100

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Length: 244, dtype: float64

In [36]:
df['bonkörlük_yüzdesi'] = df['tip'] / df['total_bill'] * 100

In [37]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bonkörlük,bonkörlük_yüzdesi
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765,14.680765

In [40]:
df.drop('Payment ID',axis = 1) #inplace = True dersek kalıcı hale getiri.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,bonkörlük,bonkörlük_yüzdesi
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,5.944673,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,16.054159,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,16.658734,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,13.978041,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,14.680765,14.680765
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,20.392697,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,7.358352,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,8.822232,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,9.820426,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,15.974441,15.974441

In [51]:
df.drop(['Payer Name','bonkörlük_yüzdesi'],axis=1)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID,bonkörlük
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251,14.680765
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672,15.974441

# Row(Satır) İşlemleri

In [52]:
# satır çekme işlemi .loc ve .ilock metodlarıyla yapılır.

In [53]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [57]:
df.set_index('Payer Name', drop =True,inplace= True)
#payer name sutünunu index yapar ve index olmayan kısmını drop ile düşürür.

In [58]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID,bonkörlük,bonkörlük_yüzdesi
Payer Name,,,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959,5.944673,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608,16.054159,16.054159
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458,16.658734,16.658734

In [62]:
#df.ilock integer location demek
df.iloc[0]

total_bill                      16.99
tip                              1.01
sex                            Female
smoker                             No
day                               Sun
time                           Dinner
size                                2
price_per_person                 8.49
CC Number            3560325168603410
Payment ID                    Sun2959
bonkörlük                    5.944673
bonkörlük_yüzdesi            5.944673
Name: Christy Cunningham, dtype: object

In [64]:
df.loc['Christy Cunningham']
#df.loc ise direk locationu vermemiz gerekir indexin

total_bill                      16.99
tip                              1.01
sex                            Female
smoker                             No
day                               Sun
time                           Dinner
size                                2
price_per_person                 8.49
CC Number            3560325168603410
Payment ID                    Sun2959
bonkörlük                    5.944673
bonkörlük_yüzdesi            5.944673
Name: Christy Cunningham, dtype: object

In [65]:
df.head(7)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID,bonkörlük,bonkörlük_yüzdesi
Payer Name,,,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959,5.944673,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608,16.054159,16.054159
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458,16.658734,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260,13.978041,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251,14.680765,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,Sun9679,18.623962,18.623962
Kristopher Johnson,8.77,2.00,Male,No,Sun,Dinner,2,4.38,2223727524230344,Sun5985,22.805017,22.805017

In [67]:
df.iloc[2:6]
# 2. ile 5. satırı çekme

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID,bonkörlük,bonkörlük_yüzdesi
Payer Name,,,,,,,,,,,,
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458,16.658734,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260,13.978041,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251,14.680765,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,Sun9679,18.623962,18.623962

In [68]:
df.loc['Travis Walters':'Erik Smith']
#iloc kullanarak 4 satırı çekme sadece stop noktaları farklı.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID,bonkörlük,bonkörlük_yüzdesi
Payer Name,,,,,,,,,,,,
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458,16.658734,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260,13.978041,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251,14.680765,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,Sun9679,18.623962,18.623962

In [69]:
df.drop('Travis Walters')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID,bonkörlük,bonkörlük_yüzdesi
Payer Name,,,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959,5.944673,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608,16.054159,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260,13.978041,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251,14.680765,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,Sun9679,18.623962,18.623962
...,...,...,...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657,20.392697,20.392697
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766,7.358352,7.358352
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880,8.822232,8.822232
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17,9.820426,9.820426
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672,15.974441,15.974441

In [72]:
df.set_index('CC Number',drop = True,inplace=True)

In [74]:
df.iloc[10:18]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payment ID,bonkörlük,bonkörlük_yüzdesi
CC Number,,,,,,,,,,,
566287581219,10.27,1.71,Male,No,Sun,Dinner,2,5.14,Sun2546,16.650438,16.650438
4577817359320969,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Sun6686,14.180374,14.180374
577040572932,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Sun1300,10.181582,10.181582
6011163105616890,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Sun2971,16.277808,16.277808
30016702287574,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Sun3848,20.364127,20.364127
180073029785069,21.58,3.92,Male,No,Sun,Dinner,2,10.79,Sun1878,18.164968,18.164968
4240025044626033,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Sun9715,16.166505,16.166505
6521340257218708,16.29,3.71,Male,No,Sun,Dinner,3,5.43,Sun2998,22.774708,22.774708

# DataFrame'de Sorgu İşlemleri

In [76]:
df=pd.DataFrame({'year':[1776,1867,1821],'pop':[328,38,126],'GDP':[20.5,1.7,1.22]} , index=['USA','CANADA','MEXICO'] )
df

        year  pop    GDP
USA     1776  328  20.50
CANADA  1867   38   1.70
MEXICO  1821  126   1.22

In [77]:
#hangi ülkelerin 50 milyondan daha fazla popülasyonu var ?

In [80]:
df[df['pop'] > 50]

        year  pop    GDP
USA     1776  328  20.50
MEXICO  1821  126   1.22

In [82]:
df[df['year']>1800]

        year  pop   GDP
CANADA  1867   38  1.70
MEXICO  1821  126  1.22

In [85]:
df = pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [86]:
df[df['total_bill']>40]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [87]:
df[df['sex']=='Male']

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [90]:
df[(df['sex']=='Female') & (df['tip']>5)]
# & sembolü and yerine kullanırız ve parantezde göstermek zorundayız

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374

In [95]:
df[(df['day']=='Sun') & (df['total_bill']>30)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3572865915176463,Sun591
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3577115550328507,Sun9335
175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,370307040837149,Sun5109
179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.32,Brian Bailey,346656312114848,Sun9851
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987

In [96]:
#veya | sembolü ile yapılır

In [98]:
df[(df['day'] ==  'Sat') | (df['day'] == 'Sun')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [101]:
df[df['day'].isin(['Sat','Sun','Thur'])]
# 3 tane veyalı sorgu yerine .isin methodu kullanılır
# içinde var mı demek.

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672